adminUser: pavel
adminPassword: qweasd   # в реальности используй secret

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  size: 5Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        url: http://victoria-metrics-victoria-metrics-single.monitoring:8428
        access: proxy
        isDefault: true
      - name: OpenSearch
        type: opensearch
        url: http://opensearch-cluster-data.monitoring:9200
        access: proxy
        database: "_all"
        jsonData:
          timeField: "@timestamp"
